site_name: Circom 2 Documentation
site_url: https://minaminao.github.io/circom/
theme:
     name: material
     palette:
          primary: blue
     # logo: assets/logo.png
     # favicon: images/favicon.png
     features:
          - navigation.tabs
          - navigation.tabs.sticky
          - navigation.tracking
repo_url: https://github.com/minaminao/circom
markdown_extensions:
     - pymdownx.arithmatex:
          generic: true
extra_javascript:
     - https://polyfill.io/v3/polyfill.min.js?features=es6
     - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
     social:
          - icon: fontawesome/brands/telegram
            link: https://t.me/iden3io
          - icon: fontawesome/brands/github
            link: https://github.com/iden3/circom
          - icon: octicons/browser-24
            link: https://iden3.io/circom

nav:
     - はじめに:
          - インストール: 'getting-started/installation.md'
          - 回路の記述: 'getting-started/writing-circuits.md'
          - 回路のコンパイル: 'getting-started/compiling-circuits.md'
          - ウィットネスの計算: 'getting-started/computing-the-witness.md'
          # - Testing circuits: 'getting-started/testing-circuits.md'
          - ゼロ知識による回路の証明: 'getting-started/proving-circuits.md'
     - ゼロ知識の背景: 'background/background.md'
     - circom言語:
          - シグナル:
               - シグナル: 'circom-language/signals.md'
               - Variables & Mutability: 'circom-language/variables-and-mutability.md'
          - テンプレート:
               - Templates & Components: 'circom-language/templates-and-components.md'
               - Pragma: 'circom-language/pragma.md'
               - Functions: 'circom-language/functions.md'
               - Include: 'circom-language/include.md'
               - The main Component: 'circom-language/the-main-component.md'
          - Syntax:
               - Comment Lines: 'circom-language/comment-lines.md'
               - Identifiers: 'circom-language/identifiers.md'
               - Reserved-keywords: 'circom-language/reserved-keywords.md'
          - Basic Operators: 'circom-language/basic-operators.md'
          - Constraint Generation: 'circom-language/constraint-generation.md'
          - Control Flow: 'circom-language/control-flow.md'
          - Data Types: 'circom-language/data-types.md'
          - Scoping: 'circom-language/scoping.md'
          - Code Quality:
               - Code Assertion: 'circom-language/code-quality/code-assertion.md'
               - Debugging Operations: 'circom-language/code-quality/debugging-operations.md'
          - Circom Insight:
               - Compiler Phases: 'circom-language/circom-insight/circom-phases.md'
               - Compiler Messages: 'circom-language/circom-insight/compiler-messages.md'
               - Unknowns : 'circom-language/circom-insight/unknowns.md'
               - Circom Library: 'circom-language/circom-insight/circom-library.md'
     - More circuits: 
          - Basic circuits: 'more-circuits/more-basic-circuits.md'
     - ダウンロード: 'downloads/downloads.md'